# Generated by Django 2.0.2 on 2019-03-15 21:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0002_auto_20190307_2149'),
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodsFav',
            new_name='UserFav',
        ),
    ]
