# Generated by Django 2.0.2 on 2019-03-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20190320_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='signer_mobile',
            field=models.CharField(default='', max_length=11, verbose_name='收货人手机'),
        ),
    ]
