# Generated by Django 2.0.2 on 2019-03-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190320_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordergoods',
            options={'verbose_name': '订单的商品', 'verbose_name_plural': '订单的商品'},
        ),
        migrations.RenameField(
            model_name='ordergoods',
            old_name='goods_nums',
            new_name='nums',
        ),
    ]
