# Generated by Django 2.0.2 on 2019-03-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20190321_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='nums',
            new_name='goods_num',
        ),
    ]
