# Generated by Django 2.0.2 on 2019-03-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='goodsbanner',
            name='image',
            field=models.ImageField(max_length=200, upload_to='brands/', verbose_name='轮播图片'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='image',
            field=models.ImageField(help_text='品牌的图片', max_length=200, upload_to='brands', verbose_name='品牌的图片'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='goods/images/', verbose_name='图片'),
        ),
    ]
