# Generated by Django 2.0.2 on 2019-04-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_categoryad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryAd',
            new_name='IndexAd',
        ),
        migrations.AlterModelOptions(
            name='indexad',
            options={'verbose_name': '广告的商品', 'verbose_name_plural': '广告的商品'},
        ),
    ]
