# Generated by Django 2.0.2 on 2019-04-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20190408_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategorybrand',
            options={'verbose_name': '类别广告', 'verbose_name_plural': '类别广告'},
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='name',
            field=models.CharField(default='', help_text='品牌名', max_length=30, verbose_name='品牌名'),
        ),
    ]
