"""
Django settings for MxShop project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR,'apps'))
sys.path.insert(0, os.path.join(BASE_DIR,'extra_apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u=1yu)g##pm_$)$&2!@gy538a0vof4yqguw7dmr2x)xuu$$!lh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',  # 坑，记得加
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'DjangoUeditor',
    'xadmin',
    'crispy_forms',  # 记得加逗号
    'users.apps.UsersConfig',
    'user_operation.apps.UserOperationConfig',
    'trade.apps.TradeConfig',
    'goods.apps.GoodsConfig',
    'rest_framework',
    'django_filters',
    'coreschema',  # 跨URL资源共享（前后端接口）
    'rest_framework.authtoken',  # TokenAuthentication身份验证方案
    'social_django',  # 第三方登录
    'raven.contrib.django.raven_compat',  # sentry错误集成

]

#  让UserProfile覆盖User
AUTH_USER_MODEL = 'users.UserProfile'

# 重载authentication，使得手机号码可以登录。 jwt接口它默认采用的是用户名和密码登录验证，所以要自定义一个用户验证
AUTHENTICATION_BACKENDS = {
    'users.views.CustomBackend',
    # 第三方登录
    'django.contrib.auth.backends.ModelBackend',
    # 微博
    'social_core.backends.weibo.WeiboOAuth2',
    # QQ
    'social_core.backends.qq.QQOAuth2',
    # 微信
    'social_core.backends.weixin.WeixinOAuth2',
}

# 添加允许执行跨站点请求
CORS_ORIGIN_ALLOW_ALL = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 添加允许执行跨站点请求
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MxShop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media', #上传media图片使得模板显示图片
                # 第三方登录
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'MxShop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        # 自带
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),

        # 本地
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mxshop',        #数据库名字
        'USER': 'root',          #账号
        'PASSWORD': 'root',    #密码
        'HOST': '127.0.0.1',     #IP
        'PORT': '3306',          #端口

        # 这里引擎用innodb（默认myisam）
        # 因为后面第三方登录时，要求引擎为INNODB
        # 'OPTIONS':{'init_command': 'SET storage_engine=INNODB'}, #这样设置会报错，改为
        "OPTIONS":{"init_command":"SET default_storage_engine=INNODB;"}

        #服务器
        # 'ENGINE': 'django.db.backends.mysql',
        # 'NAME': 'MxShop',        #数据库名字
        # 'USER': 'root',          #账号
        # 'PASSWORD': 'tml15625873905',    #密码
        # 'HOST': '120.79.43.26',     #IP
        # 'PORT': '3306',          #端口
        #
        # # 这里引擎用innodb（默认myisam）
        # # 因为后面第三方登录时，要求引擎为INNODB
        # # 'OPTIONS':{'init_command': 'SET storage_engine=INNODB'}, #这样设置会报错，改为
        # "OPTIONS":{"init_command":"SET default_storage_engine=INNODB;"}
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False  # 默认是Ture，时间是utc时间，由于我们要用本地时间，所用手动修改为false！！！！


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # 收集静态文件，先上传，执行命令。再注释，再次上传
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

MEDIA_URL = '/media/'# 上传图片的路径，上传的图片会自动传递给media目录
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')#让django识别media是存放文件的

# drf分页
# REST_FRAMEWORK = {
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',  # 开启分页
#     'PAGE_SIZE': 10,  # 每页显示商品的个数
# }

# drf验证
REST_FRAMEWORK = {
    # 验证用户登录信息
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',  # HTTP基本身份验证
        # 默认后端进行验证：CSRF令牌
        'rest_framework.authentication.SessionAuthentication',

        # 如果使用全局的TokenAuthentication，在用户登录失败或者输入过期验证码的时候，访问不了所有的页面。所以要单独接口验证登录
        # 'rest_framework.authentication.TokenAuthentication',  # 永久存储数据库，不能单点登录
    ),
    # 限速设置
    'DEFAULT_THROTTLE_CLASSES': (
            'rest_framework.throttling.AnonRateThrottle',  # 未登陆用户
            'rest_framework.throttling.UserRateThrottle'  # 登陆用户
        ),
    # 限速次数
    'DEFAULT_THROTTLE_RATES': {
        'anon': '3/minute',  # 未登陆用户访问网页一分钟3次后，抛出429异常
        'user': '6/minute'  # 未登陆用户访问网页一分钟6次后，抛出429异常
    }
}

# JWT身份验证
import datetime
JWT_AUTH = {
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=20),  # 设置jwt码过期时间
    'JWT_AUTH_HEADER_PREFIX': 'JWT',  # 不用存储tok，单点登录，可以进行加密（通过加密储存在浏览器，再通过解密得到信息）。JWT需和前端一致
}

# 手机号码正则表达式
REGEX_MOBILE = "^1[358]\d{9}$|^147\d{8}$|^176\d{8}$"

# 云片网的 apikey
APIKEY = '828bb1c73cae18e05c184969679cbd3e'

# 支付宝相关的key
    # 如果在view用相对路径，很容易出问题
    # 如果在view用绝对路径，在本地调试或者在服务器调试都很麻烦
private_key_path = os.path.join(BASE_DIR, 'apps/trade/key/private_2048.txt')
ali_pub_key_path = os.path.join(BASE_DIR, 'apps/trade/key/alipay_key_2048.txt')

# 支付宝异步、同步URL
notify_url = "http://120.79.43.26:8001/alipay/return/"
return_url = "http://120.79.43.26:8001/alipay/return/"

# drf缓存过期时间, 单位：秒
# 这个缓存使用的是内存，每次重启之后就会失效,所以要使用redis
REST_FRAMEWORK_EXTENSIONS = {
    'DEFAULT_CACHE_RESPONSE_TIMEOUT': 5   #5s过期，时间自己可以随便设定
}

# redis缓存，数据保存到redis
# 访问不同参数（页面）redis会多增一条key。如：
# 1、不同用户过滤不同参数都可以缓存到redis。2、访问其他页码。
# 启动redis 输入命令："keys *" ，获取Django缓存的key：
    # 127.0.0.1:6379> keys *
    # 1) ":1:add567be4e59d96e609eb69221a23072"
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# 第三方登录，里面的值是你的开放平台对应的值
SOCIAL_AUTH_WEIBO_KEY = '2392794455'
SOCIAL_AUTH_WEIBO_SECRET = '0463730f8aad338fabd367069687b9f4'

SOCIAL_AUTH_QQ_KEY = 'xxxxxxx'
SOCIAL_AUTH_QQ_SECRET = 'xxxxxxx'

SOCIAL_AUTH_WEIXIN_KEY = 'xxxxxxx'
SOCIAL_AUTH_WEIXIN_SECRET = 'xxxxxxx'

# 第三方登录成功后重定向
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/index/'

# Sentry增加函数来实现错误捕捉
RAVEN_CONFIG = {
    'dsn': 'http://47de9d4ae76c41c995c33c49d9d36e8c:7e9c35e7ad024089995695f6d3cb20bd@192.168.1.41:9000/2',

}
